version: '3.1'
services:
  fortjoy-gateway:
    restart: always
    image: 192.168.50.50:5000/fortjoy-gateway
    container_name: fortjoy-gateway
    ports:
      - 10080:10080
    networks:
      - gateway_network
networks:
  gateway_network: