version: '3.1'
services:
  fortjoy-eureka:
    restart: always
    image: 192.168.50.50:5000/fortjoy-eureka
    container_name: fortjoy-eureka
    ports:
      - 10010:10010
    networks:
      - eureka_network
networks:
  eureka_network: